### ISSUE TITLE
Memory leak when computing SOAP vectors

### ISSUE THREAD

**Issue by manucordova** [libAtoms/QUIP#235] opened 2020-09-07 08:08 UTC
Dear developers,

Upon updating to the latest version of QUIP/quippy, I noticed that computing the SOAP descriptors leads to my Python script using an additional 8 MB of memory each time the Descriptor.calc() function is called.

Am I doing something wrong or is there a deeper issue?

Here is a sample code:

    import numpy as np
    import os
    import sys
    import ase
    import ase.io
    import psutil
    import quippy
    
    struct = ase.io.read("COCAIN_nmrx_standard.cif")
    
    N = 100
    
    soapstr = "average=F normalise=T soap cutoff_dexp=3 cutoff_rate=1  cutoff_scale=2.0 central_reference_all_species=F central_weight=1.0 covariance_sigma0=0.0 atom_sigma=0.3 cutoff=4.5 cutoff_transition_width=0.5 n_max=12 l_max=9 n_species=5 species_Z={1 6 7 8 16} n_Z=1 Z={1}"
    
    desc = quippy.descriptors.Descriptor(soapstr)
    
    for _ in range(N):
        soap = desc.calc(struct, grad=False)['data']
        
        process = psutil.Process(os.getpid())
        print("{:.2f} MB".format(process.memory_info()[0]/1024/1024))

And here is the corresponding output:

    67.51 MB
    79.59 MB
    85.48 MB
    91.53 MB
    97.72 MB
    103.42 MB
    109.57 MB
    115.47 MB
    121.50 MB
    127.42 MB
    [...]

I am using Python 3.7.7 on a Macbook Pro 2019, and with QUIP compiled with the GNU gcc-9 compiler. The issue is also present on our linux cluster.

Thank you in advance for any advice!

Best regards,

Manuel

**Comment by gabor1** [comment] 2020-09-08 12:55
Thanks for the report. Would you be able to help us ascertain whether the leak is in the python part or the underlying fortran part? You can use the command line program `quip` to compute descriptors by simply running "quip" and giving it the XYZ file and passing the descriptor using the keyword `descriptor_str`. `quip --help` gives syntax and brief help on all keywords.

**Comment by gabor1** [comment] 2020-09-08 12:56
(also, presumably you do realise that the descriptors you are creating are all centered on only the H atoms, right?)

**Comment by manucordova** [comment] 2020-09-08 13:58
Thank you for your answer. I tried to generate the descriptor directly from the command line program with the following script:

    #!/bin/bash
    for i in `seq 1 100`
    do
        quip atoms_filename="COCAIN_nmrx_standard.xyz" descriptor_str="average=F normalise=T soap cutoff_dexp=3 cutoff_rate=1  cutoff_scale=2.    0 central_reference_all_species=F central_weight=1.0 covariance_sigma0=0.0 atom_sigma=0.3 cutoff=4.5 cutoff_transition_width=0.5 n_max=1    2 l_max=9 n_species=5 species_Z={1 6 7 8 16} n_Z=1 Z {1}"
        ps x -o rss,vsz,command | grep Terminal >> tmp.dat
    done

And the memory usage written in tmp.dat reads:

    RSS    VSZ    COMMAND
    598268  6386956 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    629320  6425068 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    648896  6444684 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    667692  6462072 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    [...]
    2389932  8289496 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    2409448  8309080 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    2428880  8328664 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    2349260  8349820 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal

I tried redirecting the output of the quip command to /dev/null, and the memory usage remained pretty much constant:

    RSS    VSZ    COMMAND
    624524  6516348 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    624524  6516348 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    624524  6516348 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    647348  6516372 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    [...]
    552172  6411828 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    552172  6411828 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    552152  6411304 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
    552152  6411304 /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal

It seems that writing the output to the prompt is the main hit on memory usage, so I assume it is an issue with the python part ?

And yes I only need the descriptors around H atoms, they are used to predict 1H NMR shifts.

Let me know if I can run any other test to help you locate the issue,

Best regards,

Manuel

**Comment by gabor1** [comment] 2020-09-08 14:03
There is no python at all when you call quip from the command line. So the small increase you are seeing must be just Terminal remembering its scroll back.. 


So at least you have a way of computing the descriptors. 

Thanks again for the report! 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by gabor1** [comment] 2020-09-08 16:16
we still might want to track down the memory leak so I'm reopening.

**Comment by mcaroba** [comment] 2020-10-24 07:51
I'm also experiencing this problem when using the soap_turbo descriptor from the GAP turbosoap branch. This seems to be a general problem, not specific to soap. In my case this is limiting because I am constructing the descriptors as part of a Python workflow, and I construct so many that I'm exceeding Slurm memory limits. I have tried garbage collection in the Python script ( `gc.collect()`) but it doesn't work. I have also tried `del` on the `Descriptor()` objects, but that doesn't work either. I have the [output](http://users.aalto.fi/~carom1/massif.out.56630) from valgrind's massif tool, if that could help someone debug this issue (if you used `ms_print` on the valgrind output, you can see the memory allocation increasing in the parts of the code where descriptors are built).

**Comment by jameskermode** [comment] 2020-10-24 07:53
I’d be happy to take a look at the valgrind output. I suspect the leak will be in the Fortran/Python interface layer.

**Comment by jameskermode** [comment] 2020-10-24 07:54
Can you also post a minimal Python script that shows the problem?

**Comment by mcaroba** [comment] 2020-10-24 08:11
The valgrind output is linked. I will write an example with regular soap
and send it later when I get a chance (I assume you don't have soap_turbo).

**Comment by jameskermode** [comment] 2020-10-24 08:17
Thanks- yes standard soap please, and with a self-contained input structure if possible to make it as simple as possible.

**Comment by mcaroba** [comment] 2020-10-24 09:02
This will do the trick:

    from ase.io import read
    from quippy.descriptors import Descriptor
    from quippy.convert import ase_to_quip
    
    soap_O = 'soap n_max=20 l_max=20 cutoff=5.0 atom_sigma=0.2 species_Z={1 6 8} n_species=3 Z=8 n_Z=1'
    d_O = Descriptor(soap_O)
    
    atoms = read("63.xyz")
    atoms.center(vacuum = 5.)
    
    for i in range(0,1000):
        at_quip = ase_to_quip(atoms)
        at_quip.set_cutoff(5.)
        at_quip.calc_connect()
        qs = d_O.calc_descriptor(at_quip)

You need this `63.xyz` file:

              12
     This passivated cluster structure was generated with Miguel Caro's carve.f90 code
     O    0.0000000000000000        0.0000000000000000        0.0000000000000000
     C   0.10856221999999960      -0.86975161000000156        2.2059415299999996
     C   -1.1084532700000000      -0.40254705000000079        2.4969244599999998
     C   -2.2673640200000005        7.1217399999996545E-003   3.0026710000000003
     C   0.99439498999999998       -1.4980180599999997        3.2329013600000005
     C   0.61373911000000003      -0.91039819999999949	 0.79959516999999991
     O    1.4876816999999996       -1.6706659899999998	 0.43379143000000031
     H   0.40323913000000022      -0.10716064000000003	-0.88544277000000093
     H  -2.2543189905359715       0.75875061215133577        3.4975284196218475
     H  -2.8856922756040650      -0.56954223428870443        3.3111006177074951
     H   1.3114743680829613       -1.1399364182294789        3.9952911591326039
     H   1.1470365410216172       -2.3698679562094318        3.3959299322850991

The 1000 iterations are there to fill the memory, in my code I loop over different structures, but always overwriting the `qs` and `d_O` objects, as in the example above. The point is that when these objects are overwritten, then memory is not freed.

**Comment by mcaroba** [comment] 2020-10-24 09:05
Actually, I just noticed I'm not overwriting `d_O` in the example whereas I do in my code. It doesn't matter, I tried both ways in my code (creating a new `d_O` or using the same one) and I ended up with the memory issues either way.

**Comment by jameskermode** [comment] 2020-10-24 09:15
Thanks, I’ll take a look, probably on Monday

**Comment by jameskermode** [comment] 2020-10-24 09:17
Can you confirm there’s no leak if you comment out the descriptor calc, i.e. from the neighbour list call alone?

**Comment by mcaroba** [comment] 2020-10-24 10:25
Yes, I can confirm. If I comment out the descriptor calc the job dies out of time limit, not memory limit.

**Comment by jameskermode** [comment] 2020-10-27 10:53
I've reproduced the problem, with debugging symbols included so we can also see where the allocations happen

```
--------------------------------------------------------------------------------
  n        time(i)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0              0                0                0             0            0
  1    991,427,221       16,535,776       16,370,797       164,979            0
  2  2,098,005,062       35,707,656       35,580,541       127,115            0
99.64% (35,580,541B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->56.83% (20,291,568B) 0x38DE4196: __descriptors_module_MOD_soap_calc (descriptors.f95:7016)
```

This corresponds to the allocation of `global_fourier_so3_r_array` and related arrays, so it seems these are not be being correctly freed when `soap_calc()` is invoked from Python. I can't immediately see why this would be, so I'll dig a bit more. 

@albapa, any ideas off the top of your head?

**Comment by albapa** [comment] 2020-10-27 11:20
Is this at line 7016? It's when we allocate the descriptor data object. My understanding is that from python we call `descriptor_calc_array()` which should at the end clean up the temporary `my_descriptor_data` object. Is this not happening from some reason?

**Comment by mcaroba** [comment] 2020-10-27 11:24
~~The `soap_turbo` descriptor does not use the `fourier_so3` stuff (it does the basis orthonormalization internally with the TurboGAP routines), yet it shows the same issue with memory leakage. Could it be a more generic problem?~~ I realized `fourier_o3` is the generic reference to the expansion coefficients - nevermind.

**Comment by albapa** [comment] 2020-10-27 11:24
Actually, not. We need to actively destroy `descriptor_out_raw` using the `finalise()`. Is this wrapped in quippy?

**Comment by jameskermode** [comment] 2020-10-27 11:25
I just looked at the Python code, it calls `descriptor_calc`, not `descriptor_calc_array`, and in any case`finalise()` should be invoked, but it seems it might not be, so I'll dig into why this might be.

**Comment by albapa** [comment] 2020-10-27 11:26
We just need to manually finalise `descriptor_out_raw`.

**Comment by albapa** [comment] 2020-10-27 11:26
> I just looked at the Python code, it calls `descriptor_calc`, not `descriptor_calc_array`, and in any case`finalise()` should be invoked, but it seems it might not be, so I'll dig into why this might be.

It used to call `descriptor_calc_array` but at the big rewrite this was changed.

**Comment by jameskermode** [comment] 2020-10-27 11:28
> We just need to manually finalise descriptor_out_raw.

Python garbage collection should take care of this, but somehow is not. I think the relevant `finalise()` is not being found when generating the wrappers for some reason.

**Comment by jameskermode** [comment] 2020-10-27 11:28
in any case, I'll be able to fix it now I know where the problem is - thanks @mcaroba for the detailed report.

**Comment by jameskermode** [comment] 2020-10-27 11:33
I was wrong about the `global_fourier_so_3`, hadn't pulled GAP on the laptop I was reading the code on as recently as the computer where I ran the test... @albapa is right that it's the the allocation of `descriptor_out` itself, which makes more sense and is consistent with it not being finalised from Python.

**Comment by jameskermode** [comment] 2020-10-27 11:53
OK, the issue is that Python didn't allocate the memory, so doesn't think it should free it, which is wrong in this case, since `descriptor_calc()` should be viewed as an alternative constructor, where Fortran allocates the memory, but it then belongs to the Python user. I'll check in a fix, most likely in `f90wrap` to fix the more general case since this applies to any subroutine/function with an `intent(out)` derived type argument.

**Comment by noambernstein** [comment] 2020-10-27 12:04
On Tue, Oct 27, 2020 at 7:53 AM James Kermode <notifications@github.com>
wrote:

> I'll check in a fix, most likely in f90wrap to fix the more general case
> since this applies to any subroutine/function with an intent(out) derived
> type argument.
>
is this necessary or sufficient? Derived types with no allocable components
shouldn’t require this, should they? And primitive type that are
allocatable should, no?

Not sure what to do if this is correct. Parse to see if allocate is called?
Require some manual hint, since the allocate could be called in some deeper
routine where you couldn’t find it?

>

**Comment by jameskermode** [comment] 2020-10-27 12:21
> is this necessary or sufficient? Derived types with no allocable components
shouldn’t require this, should they? And primitive type that are
allocatable should, no?

I think the proposed fix in jameskermode/f90wrap#131 should work in general, since it will ensure the Fortran destructor (`descriptor_finalise()` in this case) is called when the Python objects is garbage collected. If there's no Fortran destructor, then nothing needs to be done.

Testing now, will report back here.

**Comment by jameskermode** [comment] 2020-10-27 12:26
Yup, that seems to have fixed it. @mcaroba, would you be willing to test with that branch of `f90wrap` to confirm? It needs a `make clean` to rebuild quippy fully. If so then I'll merge the f90wrap PR and try to remember how to update the QUIP submodule which points to it.

**Comment by mcaroba** [comment] 2020-10-27 14:30
@jameskermode Yes, this seems to work, thanks! (Note: I always build f90wrap with the setup.py and update the command info in quippy's Makefile, so I haven't tested anything other than the f90wrap binary on its own).

**Comment by jameskermode** [comment] 2020-10-27 14:41
Great, thanks for the confirmation. I'll merge the f90wrap PR, then try to update the link here.

**Comment by jameskermode** [comment] 2020-10-27 15:56
f90wrap submodule updated in `public`. Reopen if there are any further issues.

**Comment by albapa** [comment] 2020-12-03 18:50
On my Mac, with a freshly upgraded f90wrap, fresh QUIP/quippy I am getting a memory leak when calculating descriptors repeatedly. Does anyone have a similar issue?

**Comment by albapa** [comment] 2020-12-03 18:57
Running this I can see the memory usage growing:
```
from ase.build import bulk
from quippy.descriptors import Descriptor

a0 = bulk("Si",cubic=True)
desc = Descriptor("soap atom_sigma=0.5 l_max=6 n_max=10 cutoff=4.5")

for i in range(10000):
    d = desc.calc(a0)
```

**Comment by jameskermode** [comment] 2020-12-03 19:07
That sounds like it should be related to this issue. Are you sure you're using the updated f90wrap, rather than one installed locally with `pip`? If so, are you willing to compile with debug symbols and run with valgrind: something like `massif python script.py`?

**Comment by albapa** [comment] 2020-12-03 19:10
I'm using
```! f90wrap -V
f90wrap v0.2.3```

**Comment by albapa** [comment] 2020-12-03 19:11
For the debug symbols, is there anything special or just `-g` in the Makefile.inc?

**Comment by jameskermode** [comment] 2020-12-03 19:13
Just `-g`. 

I didn't make a new release so the f90wrap version is very likely the problem. Can you try using the pinned version in QUIP/src/f90wrap (check the quippy/Makefile to see how it look for it), or clone the latest master branch from https://github.com/jameskermode/f90wrap/ and then do a `pip install .` from inside it.

**Comment by jameskermode** [comment] 2020-12-03 19:16
You might need to do `git submodule update` from QUIP directory to update the linked version.

**Comment by albapa** [comment] 2020-12-03 20:26
If I use the development version, I get the quite sinister error:

```
import quippy

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-b3ccdec535f6> in <module>
----> 1 import quippy

~/miniconda3/lib/python3.7/site-packages/quippy-git_github.com_libAtoms_QUIP.git_357e28d15_dirty-py3.7-macosx-10.9-x86_64.egg/quippy/__init__.py in <module>
     40 
     41 import quippy.convert
---> 42 import quippy.potential
     43 import quippy.descriptors
     44 import quippy.nye_tensor

~/miniconda3/lib/python3.7/site-packages/quippy-git_github.com_libAtoms_QUIP.git_357e28d15_dirty-py3.7-macosx-10.9-x86_64.egg/quippy/potential.py in <module>
     41 Pythonic interface to auto-generated quippy.potential_module.Potential class
     42 """)
---> 43 class Potential(ase.calculators.calculator.Calculator):
     44     callback_map = {}
     45 

~/miniconda3/lib/python3.7/site-packages/quippy-git_github.com_libAtoms_QUIP.git_357e28d15_dirty-py3.7-macosx-10.9-x86_64.egg/quippy/potential.py in Potential()
    112                               'atoms': {}}
    113 
--> 114     @set_doc(quippy.potential_module.Potential.calc.__doc__,
    115     """
    116     Pythonic wrapper to `quippy.potential_module.Potential.calc()`

AttributeError: type object 'Potential' has no attribute 'calc'
```

**Comment by jameskermode** [comment] 2020-12-03 20:37
That is correct - `quippy.potential.Potential` is a thin ASE-compatible wrapper. The true QUIP potential is in `quippy.potential_module.Potential`

**Comment by jameskermode** [comment] 2020-12-03 20:39
oh no, sorry, that's not good at all - reading more carefully I see this error occurs on import. Something is messed up with your Python packages, I suggest removing everything quippy related from your site-packages directory and reinstalling.

**Comment by jameskermode** [comment] 2020-12-03 20:55
It’s possible the PR I just merged into f90wrap has broken something; bet bet would be to use the exact version linked to QUIP.

**Comment by albapa** [comment] 2020-12-03 22:36
It seems all is well if I use the exact version linked to QUIP. I am not sure if I did it well, but in the end I pip installed it from src/f90wrap and now there is no more memory leak.

**Comment by jameskermode** [comment] 2020-12-04 07:32
Ok, good to know. I’ll fix whatever is wrong with the latest devel version and then make a new release so that `pip install f90wrap` is compatible with quip.

**Comment by albapa** [comment] 2020-12-04 09:31
Thanks!

**Closed as completed by albapa** 2020-12-04 09:31 UTC

**Comment by richardjana** [comment] 2021-02-26 13:54
I recently had a related problem with memory leaks from quippy. It seemed like the problem would be in the f90wrap, so I posted there: [f90wrap issue 143](https://github.com/jameskermode/f90wrap/issues/143). It has not been solved yet, but some of you might still be interested.
