### ISSUE TITLE
OpenBLAS Warning when use quippy

### ISSUE THREAD

**Issue by bigd4** [libAtoms/QUIP#407] opened 2022-02-15 01:26 UTC
I install quippy by `pip install quippy-ase` and when I test GAP potential, I got `OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.`  both in Ubuntu and CentOS. I can get the correct energy and forces but how can I solve this warning?

**Comment by jameskermode** [comment] 2022-02-15 07:49
Duplicate of https://github.com/libAtoms/quippy-wheels/issues/4

you can ignore safely ignore this warning, although I agree it would be nice to get rid of it.

**Closed as completed by jameskermode** 2022-02-15 07:49 UTC

**Comment by laigner** [comment] 2022-05-30 22:17
Hey,

is there a way to get rid of this warning? I am using the quippy potential with ASE to simulate a system and it is much slower due to the 1000 warning prints within each simulation step. I would really appreciate a fix or a work around of this. Does anybody has a suggestion?

Greetings,
Lukas

**Comment by gabor1** [comment] 2022-05-30 22:29
Can you link with a non-omp version of blas libraries?

**Comment by laigner** [comment] 2022-05-31 13:20
Thanks for the fast reply. Due to the fact that I installed it via pip and never touched openblas and don't know where to link those libraries, I decided to build QUIP, quippy and GAP from source without the openmp arch, what solved it.
