### ISSUE TITLE
AtomsWriter has no default format for "stdout"

### ISSUE THREAD

**Issue by noambernstein** [libAtoms/QUIP#20] opened 2016-01-07 14:03 UTC
AtomsWriter("stdout") used to work, and defaulted to extxyz format.  Now it is unable to figure out what format to use, so it fails.  I suspect this has to do with integration of ASE's I/O routines.

tin 1001 : python
Python 2.7.10 (default, Nov 19 2015, 09:31:54) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from quippy import AtomsWriter
> > > aw = AtomsWriter("t.xyz")
> > > aw = AtomsWriter("stdout")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/quip/2015-12-17/mkl/lib/python/quippy/io.py", line 587, in AtomsWriter
> > >     raise ValueError("Don't know how to write Atoms to format %r" % format)
> > > ValueError: Don't know how to write Atoms to format 'stdout'

**Comment by jameskermode** [comment] 2016-01-11 17:44
Thanks for spotting this regression, indeed due to using ASE I/O. Fixed in commit af6e17e2d. `convert.py` and `AtomsWriter()` both understand `stdout` again, and convert.py allows the shortcut `-` on command line.

**Comment by noambernstein** [comment] 2016-01-11 18:48
I just noticed the commit that claims to fix the problem in the original
response, but I don't see this commit, despite just having done a git merge
from public.

**Comment by jameskermode** [comment] 2016-01-11 18:49
It's on public at gc121mac1 repo, not yet on GitHub

**Comment by noambernstein** [comment] 2016-01-11 18:54
OK, now I see the commit, and it works.

**Comment by jameskermode** [comment] 2016-01-11 18:56
Good. Closing now.

**Closed as completed by jameskermode** 2016-01-11 18:56 UTC
